### ISSUE TITLE
release 2.0.0

### ISSUE THREAD

**Issue by vchebotarev** [FoolCode/SphinxQL-Query-Builder#150]
@oohnoitz What do you think about it ?
But there are still some issues #110 #132 #141 which should be managed before or not ...

**Comment by oohnoitz** [comment]
Here is my thoughts on those 3 open issues.

- #110 shouldn't take much effort to implement and should be included in the release.
- #132 might require some tinkering so that the API doesn't seem awkward. I'd rather punt this off for now.
- #141 isn't required and just a nice to have.

I think the only major blockers is making sure all documentation is up-to-date and noting all of the breaking changes somewhere. I'd also have to generate a new `CHANGELOG` since the current one hasn't been maintained for a while. It'd be ideal to mention all of the breaking changes and migration paths in the new release. Since most of the changes have been done by you, can you write up a quick breakdown on the recent changes including any additional documentation changes that might need to be made?

**Comment by vchebotarev** [comment]
Sorry for delay.
So, i dont quiet understand how to generate changelog correctly. May be i'll write down what was done since last realese and you will formalize it in the correct way

**Comment by vchebotarev** [comment]
- phpDoc update
- \Foolz\SphinxQL\Drivers\ResultSetAdapterInterface constants were removed. Fetch type argument became boolean (assoc or not)
- global refactor of dependencies between classes and implemented interfaces to avoid code dublicating
- fixed incorrect property visibility
- removed connection error supressing in during connection, fixed exception throwing
- dropped static creational methods
- php 5.6 is a minimum requirent, dropped support of HHVM

something like that ...

**Comment by oohnoitz** [comment]
No problem, I'll formalize it once I have the chance. It's just that I wanted to make sure what the actual breaking changes were so that it can be surfaced up in the CHANGELOG as to what they would actually need to fix.

Will move that one line from the README before I publish a new release. I think the only other thing I'd like to get in is #153 which just needs some adjustments to tests/CI.

**Comment by oohnoitz** [comment]
The 3 open issues I mentioned above should be addressed. The only thing left would be #153 before I'll update the changelog and create a tag release.

**Comment by oohnoitz** [comment]
I created a tag for `2.0.0`.

https://packagist.org/packages/foolz/sphinxql-query-builder#2.0.0
