### ISSUE TITLE
excessive escaping

### ISSUE THREAD

**Issue by KarelWintersky** [FoolCode/SphinxQL-Query-Builder#177]
I recieving from `$_GET['subway']` : 
```
array(2) {
  [0]=>
  string(2) "17"
  [1]=>
  string(2) "64"
}
```
as result of query `subway[0]=17&subway[1]=64`

then, I use:
```
$query_data = $query_data->where('subway', 'IN', $_REQUEST['subway']);
```
and have error:
```
SELECT * FROM rt_dp_clinics WHERE subway IN (''17'',''64'')  ORDER BY nreplies DESC OPTION field_weights=(title=20, short=10, text=5);  /* error=index rt_dp_clinics: unsupported filter type '(filter-type-6)' on int column */
```

Please, check type of variables while escaping it.

**Comment by KarelWintersky** [comment]
My solution is:

```
$query_data = $query_data->where('subway', 'IN', array_map(function ($i){ return intval($i); }, $_REQUEST['subway']));
```
but it is excessive

**Comment by KarelWintersky** [comment]
Excessive escaping? 

Double escaping of strings is not a responsibility of builder? Really?

**Comment by oohnoitz** [comment]
I'd have to agree with @glukkkk on this. Honestly, I would love to rip out a bunch of the escaping logic we have and since it's caused quite a bit of problems with `MATCH` in certain use cases. There's only so many cases that we can only think of and I don't have any solution at this time.

I don't have PHP installed on my environment, but I would have thought that it'd compile the `WHERE` to `subway IN ('17', '64')`. However, I don't think `WHERE IN` even allows string inputs to be accepted in that syntax. Other than that, you should be preparing/sanitizing your input before passing them into the builder. Using input directly from `$_GET` and `$_REQUEST` without any preparation is considered dangerous.

**Comment by KarelWintersky** [comment]
@oohnoitz , some PHP methods returns strings instead of integer. 

So, Build MUST check type of variable before escaping it: 

`if (! is_string($value)) escape this. `

**Comment by woxxy** [comment]
`WHERE IN` requires numeric values. You should process the input for it to be numeric. The library will not guess which conversions to make for you, because it won't know how (is it int? float? decimal? hex?).

The query erroring is the desired behaviour - the escaping prevents injection, not bad queries.

About `(''17'',''64'')`, did it actually have double single quotes?

**Comment by KarelWintersky** [comment]
> About (''17'',''64''), did it actually have double single quotes?

Yeah. I is double single quotes.

**Comment by woxxy** [comment]
> > About (''17'',''64''), did it actually have double single quotes?
> 
> Yeah. I is double single quotes.

That is what's worrying me now, it should be single at best.

**Comment by oohnoitz** [comment]
I used Travis CI to confirm my assumptions, and it seems to be working properly and as intended. So there isn't any "double single quotes" happening:

- https://github.com/FoolCode/SphinxQL-Query-Builder/commit/a5be5fdeacc9bfaa1f2706a1bd2e99903407c6a0
- https://travis-ci.org/FoolCode/SphinxQL-Query-Builder/builds/551331692

As @woxxy has mentioned, we won't make any type of assumptions and perform any automatic conversions as we can't account for every single use case. The query builder is performs single escape/quoting logic for almost every query besides `MATCH` as that is a bit more complex.

Just to clarify, we assumed the issue was with the value being quoted twice with a single quote, like `''11''` which are two single quotes next to each other, and not double quotes, like `"11"` which is just double quotes on each side of the value. These are two different things you might be mixing up.

**Comment by KarelWintersky** [comment]
so. i'll close issue. If i found this problem again, i will reopen it.
