### ISSUE TITLE
Search with Facets

### ISSUE THREAD

**Issue by vizzent** [FoolCode/SphinxQL-Query-Builder#46]
Hello and congratulations for this tool. :package: :+1: 

I want to know if there are some way to get a query's facets. Has it implemented?

Thanks!

**Comment by woxxy** [comment]
Hey, thank you!

Faceted search is not yet not implemented, but it should be fairly easy to implement.

All we need to do is adding something like `FACET $name` at the end of the SphinxQL string, I guess.

**Comment by woxxy** [comment]
Actually `FACET` adds a lot of complexity since we can't expect a fixed amount of results. More precisely: we need to merge query and multiQuery.

This might be extremely unstable under `PDO` driver.

**Comment by vizzent** [comment]
I need to use it in my project. :)

Can I help you with this?

**Comment by versh23** [comment]
yeah, PDO is not good for this(
there are more problems with PDO driver as it seemed at the first view...

**Comment by woxxy** [comment]
This may be problematic in general. I'll try getting a solution running for version 1.0.x... tonight or tomorrow.
The `->executeBatch()` method should be deprecated since it's just doubling up a pre-existing function, `->execute()`.

My only worry with PDO is that we'll be forever forced to store the results in PHP instead of using the convenient cursor solution that leaves the result in mysql.

Furthermore, the code used to expect as many results as queries queued.

Again, version 1.0.x is in beta state and we're still deciding upon the API for the `ResultSet`s. You can learn how to use the API by reading the unit tests. Use the `Mysqli` driver as it's pretty much stable.

**Comment by woxxy** [comment]
@vizzent In the `resultset` branch I added also a `facet` method. It might/will break, it needs testing.

Current usage:
```php
SphinxQL::create($conn)->select()->...->facet($name, $as)->executeBatch();
```

But this isn't really enough. The final idea should be having this:
```php
->facet(Facet::create()->by(...)->orderBy(...)->limit(...))
```
matching the SphinxQL docs: `FACET {expr_list} [BY {expr_list}] [ORDER BY {expr | FACET()} {ASC | DESC}] [LIMIT [offset,] count]`

@vizzent if you could, create a Facet class that behaves kinda like SphinxQL and returns a SQL string for the FACET query.


As facet isn't yet documented and this is branch 1.0.x the API may be changed as much as we need.

**Comment by vizzent** [comment]
@woxxy Monday morning I'll work in this! I think that it will be short. 

Thanks you!

**Comment by vizzent** [comment]
@woxxy I need permissons to push my commit on resultset branch. I have implemented the facet object.

**Comment by woxxy** [comment]
Thank you!

To merge changes on Github you must follow the [Pull Request](https://help.github.com/articles/using-pull-requests/) flow.

In short:

* fork the library with the button on the site
* $ git remote add {user} {your-fork-url.git}
* $ git push {user} {your-fork-url.git}
* go on your fork on the site
* look where to start a pull request
* follow on-screen info

That allows us to review and automatically test the code before merging

**Comment by vizzent** [comment]
@woxxy Ok! 
Now you can see the Pull Request. Thansk for your explanation. 

I can't test the object now, please tell me If you need that I fix something.

**Comment by woxxy** [comment]
This is fully implemented.
