### ISSUE TITLE
Some chars pass escapeMatch filter?

### ISSUE THREAD

**Issue by is-blackhole** [FoolCode/SphinxQL-Query-Builder#96]
Hello!
I have used your awesome package and yesterday my site sent me error about incorrect sphinx ql syntax:
```
exception 'Foolz\SphinxQL\Exception\DatabaseException'
with message '[1064] index articles,dossiers: syntax error, unexpected
')' near '?'?\")' [ SELECT id, typeof, (WEIGHT() +
IF(typeof='dossier', 5000, 0)) AS w FROM articles, dossiers WHERE
MATCH('(?\'?\\\")') 
```
Query params are search.php?q=%bf%27%bf%22 (looks like some unicode chars) and query is build using $qb->match('*',$q)
Docs says all MATCH are auto-escaped, I also tried to pass $qb->escapeMatch($q) - and still got that error.
I think some special chars can still pass through escape filter?

Thx

**Comment by oohnoitz** [comment]
@is-blackhole after doing some rudimentary tests, it looks like your query is failing because of the `%BF` url encoded character that's being passed through your query string params which doesn't appear to be decoded properly in the error message displayed. I also ran a test with the actual ASCII value for that character passed into a query string param, and it appeared to execute the query without any errors for me.

You can also take a look at https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/src/SphinxQL.php#L169-L208 to see the list of characters we escape by default, but that list only includes the special operators/modifiers used in the extended query syntax and a few other characters we considered "special".

**Comment by oohnoitz** [comment]
Going to close this since there isn't an issue with the library itself. You can use the methods available [here](https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/src/SphinxQL.php#L1204-L1234) to escape your own set of characters in a MATCH query.

**Comment by is-blackhole** [comment]
Yes, thanks for your help!
